[32mINFO    [0m pytest_operator.plugin:plugin.py:795 Connecting to existing model github-pr-48335-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:893 unexpected facade AgentLifeFlag received from the controller
[33mWARNING [0m juju.client.connection:connection.py:909 unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
[33mWARNING [0m juju.client.connection:connection.py:893 unexpected facade SecretsDrain received from the controller
[33mWARNING [0m juju.client.connection:connection.py:893 unexpected facade UserSecretsDrain received from the controller
[33mWARNING [0m juju.client.connection:connection.py:893 unexpected facade UserSecretsManager received from the controller
[32mINFO    [0m juju.model:model.py:2641 Waiting for model:
  test (missing)
[32mINFO    [0m juju.model:model.py:1988 Deploying local:jammy/test-upload-0
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller                Cloud/Region        Version  SLA          Timestamp
testing  github-pr-48335-microk8s  microk8s/localhost  3.3.7    unsupported  10:03:50Z

App   Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
test           active      1  test-upload             0  10.152.183.133  no       

Unit     Workload  Agent  Address      Ports  Message
test/0*  active    idle   10.1.63.137         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:


[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...
[1m[31mERROR   [0m websockets.client:protocol.py:1009 data transfer failed
Traceback (most recent call last):
  File "/home/runner/work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration-juju3.1/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 953, in transfer_data
    message = await self.read_message()
  File "/home/runner/work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration-juju3.1/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1023, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/runner/work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration-juju3.1/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1098, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/runner/work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration-juju3.1/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1155, in read_frame
    frame = await Frame.read(
  File "/home/runner/work/operator-workflows/operator-workflows/tests/workflows/integration/test-upload-charm/.tox/integration-juju3.1/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
[33mWARNING [0m juju.client.connection:connection.py:552 Receiver: Connection closed, reconnecting