[32mINFO    [0m pytest_operator.plugin:plugin.py:806 Connecting to existing model github-pr-8c00f-microk8s:testing on unspecified cloud
[32mINFO    [0m juju.model:model.py:2631 Waiting for model:
  test (missing)
[32mINFO    [0m juju.model:model.py:1994 Deploying local:jammy/test-upload-0
[32mINFO    [0m juju.model:model.py:2631 Waiting for model:
  test/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller                Cloud/Region        Version  SLA          Timestamp
testing  github-pr-8c00f-microk8s  microk8s/localhost  2.9.52   unsupported  05:40:32Z

App   Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
test           active      1  test-upload             0  10.152.183.138  no       

Unit     Workload  Agent  Address       Ports  Message
test/0*  active    idle   10.1.181.138         


[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

model-51c1e445-a808-4065-8fd8-7afa8517d3d3: 05:38:06 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
model-51c1e445-a808-4065-8fd8-7afa8517d3d3: 05:38:09 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [51c1e4] "model-51c1e445-a808-4065-8fd8-7afa8517d3d3" cannot open api: unable to connect to API: dial tcp 10.152.183.227:17070: connect: connection refused

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...